### ISSUE TITLE
UHFQC sequence compilation sometimes fails for no reason

### ISSUE THREAD

**Issue by AdriaanRol** [DiCarloLab-Delft/PycQED_py3#342]
Problem is that when uploading the standard program from the UHFQC LutMan the ZI sequence 
@NielsBultink Looked into this last Friday and was not able to reproduce this on the other system. 

@NielsBultink did implement the compiler API improvements that I previously made for the AWG8 such that proper erros get raised. I encountered it again this morning (2/10/2017). I did not save the traceback.

**Comment by AdriaanRol** [comment]
Got my first traceback. 

Repeated the exact same command and the second time I got no compilation error. 
```
Configuring AWG of UHFQC
---------------------------------------------------------------------------
ziShellCompilationError                   Traceback (most recent call last)
<ipython-input-14-5e1bd2ad9064> in <module>()
----> 1 QL.find_frequency()

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\meta_instrument\qubit_objects\qubit_object.py in find_frequency(self, method, pulsed, steps, freqs, f_span, use_max, f_step, verbose, update, close_fig)
    297             # args here should be handed down from the top.
    298             self.measure_spectroscopy(freqs, pulsed=pulsed, MC=None,
--> 299                                       analyze=True, close_fig=close_fig)
    300 
    301             label = 'spec'

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\meta_instrument\qubit_objects\CCL_Transmon.py in measure_spectroscopy(self, freqs, pulsed, MC, analyze, close_fig)
    812             logging.warning('CCL transmon can only perform '
    813                             'pulsed spectrocsopy')
--> 814         self.prepare_for_continuous_wave()
    815         if MC is None:
    816             MC = self.instr_MC.get_instr()

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\meta_instrument\qubit_objects\CCL_Transmon.py in prepare_for_continuous_wave(self)
    482             raise ValueError('Readout "{}" '.format(self.ro_acq_weight_type())
    483                              + 'weight type must be "SSB" or "DSB"')
--> 484         self.prepare_readout()
    485         self._prep_cw_spec()
    486         # LO for readout is turned on in prepare_readout

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\meta_instrument\qubit_objects\CCL_Transmon.py in prepare_readout(self)
    507         self._prep_ro_instantiate_detectors()
    508         self._prep_ro_sources()
--> 509         self._prep_ro_pulse()
    510         self._prep_ro_integration_weights()
    511 

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\meta_instrument\qubit_objects\CCL_Transmon.py in _prep_ro_pulse(self)
    639 
    640             ro_lm.acquisition_delay(self.ro_acq_delay())
--> 641             ro_lm.load_DIO_triggered_sequence_onto_UHFQC()
    642 
    643             UHFQC.sigouts_0_offset(self.ro_pulse_mixer_offs_I())

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\meta_instrument\LutMans\ro_lutman.py in load_DIO_triggered_sequence_onto_UHFQC(self, regenerate_waveforms, timeout)
    217                                  self._voltage_max)
    218         self.AWG.get_instr().awg_sequence_acquisition_and_DIO_triggered_pulse(
--> 219             I_waves, Q_waves, cases, self.acquisition_delay(),timeout=timeout)
    220 
    221     def load_waveforms_onto_AWG_lookuptable(

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\physical_instruments\ZurichInstruments\UHFQuantumController.py in awg_sequence_acquisition_and_DIO_triggered_pulse(self, Iwaves, Qwaves, cases, acquisition_delay, timeout)
    837                     'wait(300);\n' +
    838                     'setTrigger(0);\n')
--> 839         self.awg_string(sequence, timeout=timeout)
    840 
    841     def awg_sequence_acquisition_and_pulse(self, Iwave, Qwave, acquisition_delay):

d:\githubrepos\pycqed_py3\pycqed\instrument_drivers\physical_instruments\ZurichInstruments\UHFQuantumController.py in awg_string(self, program_string, timeout)
    337             #     print(i+1, '\t', line)
    338             # print('\n')
--> 339             raise ziShellCompilationError(comp_msg)
    340         # If succesful the comipilation success message is printed
    341         t1 = time.time()

ziShellCompilationError: Compiling string...
Syntax error while assembling machine code
Compilation failed
```

**Comment by AdriaanRol** [comment]
This is potentially caused by #348

**Comment by AdriaanRol** [comment]
This was closed when working on M18
